// Generated by CoffeeScript 1.11.1
(function() {
  var fill;

  fill = function(container, liquid) {
    if (liquid == null) {
      liquid = "coffee";
    }
    return "Filling the " + container + " with " + liquid;
  };

  module.exports = fill;

}).call(this);
